name: Pre Deploy Branch

on:
  push:
    branches:
      - develop
    paths:
      - 'front_end/**'
      - 'back_end/index.mjs'
      - 'back_end/.htaccess'
      - 'back_end/package.json'
      - 'back_end/src/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ----------------------------------------------------------------
      # front_end BUILD
      # ----------------------------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install front_end Dependencies
        working-directory: ./front_end
        run: npm ci

      - name: Build front_end
        working-directory: ./front_end
        run: npm run build

      # ----------------------------------------------------------------
      # BACKEND PREP
      # ----------------------------------------------------------------

      # ----------------------------------------------------------------
      # ARTIFACT ASSEMBLY
      # ----------------------------------------------------------------
      - name: Prepare Deployment Artifact
        run: |
          mkdir pre_deploy_artifact
          
          echo "Copying front_end..."
          # Copy front_end Build to root
          cp -r front_end/dist/* pre_deploy_artifact/
          cp front_end/.htaccess pre_deploy_artifact/

          # Copy Github Workflow so it is available in the pre_deploy branch
          mkdir -p pre_deploy_artifact/.github/workflows
          cp .github/workflows/manual_deploy.yml pre_deploy_artifact/.github/workflows/

          # Create Backend Directory
          mkdir pre_deploy_artifact/back_end
          
          # Copy Backend Files
          cp back_end/index.js pre_deploy_artifact/back_end/
          cp back_end/.htaccess pre_deploy_artifact/back_end/
          cp back_end/package.json pre_deploy_artifact/back_end/
          # cp back_end/db-reset.mjs pre_deploy_artifact/back_end/
          # cp back_end/db-sync.mjs pre_deploy_artifact/back_end/
          cp -r back_end/src pre_deploy_artifact/back_end/
          
          # Verify structure
          echo "Listing Artifact Structure:"
          ls -R pre_deploy_artifact

      - name: Deploy to pre_deploy branch
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd pre_deploy_artifact
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b pre_deploy
          git add .
          git commit -m "Pre-deploy update $(date -u)"
          # Push to the same repo
          git remote add origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          git push -f origin pre_deploy


